# Generated by Django 4.2.24 on 2025-10-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customer_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='res_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.restaurant'),
        ),
    ]
