# Generated by Django 4.2.24 on 2025-12-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='res_id',
            new_name='res',
        ),
    ]
